"""Lexicon lookup for known Hinglish words.

Loads data from two sources (in priority order):
1. HPC-generated JSON files (ipa_map.json, correction_map.json) - large, comprehensive
2. Built-in hardcoded lexicon - small, always available as fallback

Maps common Romanized Hindi words (and their spelling variants) to IPA.
This is the fastest and most accurate path - rule-based G2P is the fallback.
"""

import json
import os
from typing import Optional, Dict

_LEXICON: Optional[Dict[str, str]] = None
_CORRECTION_MAP: Optional[Dict[str, str]] = None

_LEXICON_DIR = os.path.dirname(__file__)
_IPA_MAP_PATH = os.path.join(_LEXICON_DIR, "ipa_map.json")
_CORRECTION_MAP_PATH = os.path.join(_LEXICON_DIR, "correction_map.json")
_FULL_LEXICON_PATH = os.path.join(_LEXICON_DIR, "hinglish_lexicon.json")


def _load_lexicon() -> Dict[str, str]:
    """Load the IPA lexicon from disk (lazy loading).

    Priority:
    1. ipa_map.json (generated by HPC job) - romanized -> IPA
    2. hinglish_lexicon.json (legacy format) - romanized -> {devanagari, ipa}
    3. Built-in hardcoded lexicon (always available)
    """
    global _LEXICON
    if _LEXICON is None:
        _LEXICON = {}

        # Try HPC-generated IPA map first (flat: word -> ipa)
        if os.path.exists(_IPA_MAP_PATH):
            with open(_IPA_MAP_PATH, "r", encoding="utf-8") as f:
                _LEXICON = json.load(f)

        # Try full lexicon (word -> {devanagari, ipa})
        elif os.path.exists(_FULL_LEXICON_PATH):
            with open(_FULL_LEXICON_PATH, "r", encoding="utf-8") as f:
                data = json.load(f)
            # Extract IPA values
            for key, value in data.items():
                if key.startswith("__dev__"):
                    continue
                if isinstance(value, dict) and "ipa" in value:
                    _LEXICON[key] = value["ipa"]
                elif isinstance(value, str):
                    _LEXICON[key] = value

        # Built-in OVERRIDES generated (built-in is hand-verified, more accurate)
        builtin = _get_builtin_lexicon()
        _LEXICON.update(builtin)

    return _LEXICON


def _load_correction_map() -> Dict[str, str]:
    """Load the correction map (romanized -> devanagari).

    Priority:
    1. correction_map.json (generated by HPC job)
    2. Empty dict (corrections handled by corrector.py's hardcoded map)
    """
    global _CORRECTION_MAP
    if _CORRECTION_MAP is None:
        if os.path.exists(_CORRECTION_MAP_PATH):
            with open(_CORRECTION_MAP_PATH, "r", encoding="utf-8") as f:
                _CORRECTION_MAP = json.load(f)
        else:
            _CORRECTION_MAP = {}
    return _CORRECTION_MAP


def lookup_ipa(word: str) -> Optional[str]:
    """Look up a Romanized Hindi word in the lexicon.

    Args:
        word: Lowercase romanized Hindi word

    Returns:
        IPA string if found, None otherwise
    """
    lexicon = _load_lexicon()
    return lexicon.get(word.lower().strip())


def lookup_devanagari(word: str) -> Optional[str]:
    """Look up a Romanized Hindi word's canonical Devanagari form.

    Uses the HPC-generated correction map.

    Args:
        word: Lowercase romanized Hindi word

    Returns:
        Devanagari string if found, None otherwise
    """
    correction_map = _load_correction_map()
    return correction_map.get(word.lower().strip())


def get_lexicon_stats() -> dict:
    """Get statistics about the loaded lexicon.

    Useful for debugging and reporting.
    """
    lexicon = _load_lexicon()
    correction_map = _load_correction_map()
    return {
        "ipa_entries": len(lexicon),
        "correction_entries": len(correction_map),
        "ipa_map_loaded": os.path.exists(_IPA_MAP_PATH),
        "correction_map_loaded": os.path.exists(_CORRECTION_MAP_PATH),
        "full_lexicon_loaded": os.path.exists(_FULL_LEXICON_PATH),
        "using_builtin_only": not os.path.exists(_IPA_MAP_PATH) and not os.path.exists(_FULL_LEXICON_PATH),
    }


def _get_builtin_lexicon() -> Dict[str, str]:
    """Built-in lexicon of common Hinglish words with their IPA.

    This covers the most frequent ~100 words and their spelling variants.
    The full lexicon (generated via HPC) supplements this.
    """
    return {
        # Common variants of "bahut" (very/much)
        "bahut": "b\u0259\u0266\u028at\u032a",
        "bohot": "b\u0259\u0266\u028at\u032a",
        "bohut": "b\u0259\u0266\u028at\u032a",
        "bahot": "b\u0259\u0266\u028at\u032a",
        "boht": "b\u0259\u0266\u028at\u032a",
        "bhot": "b\u0259\u0266\u028at\u032a",
        # "accha" (good)
        "accha": "\u0259t\u0361\u0283\u02d0\u02b0a\u02d0",
        "achha": "\u0259t\u0361\u0283\u02d0\u02b0a\u02d0",
        "acha": "\u0259t\u0361\u0283\u02d0\u02b0a\u02d0",
        "achaa": "\u0259t\u0361\u0283\u02d0\u02b0a\u02d0",
        "aacha": "\u0259t\u0361\u0283\u02d0\u02b0a\u02d0",
        # "kaise" (how)
        "kaise": "k\u025b\u02d0se\u02d0",
        "kese": "k\u025b\u02d0se\u02d0",
        "kayse": "k\u025b\u02d0se\u02d0",
        # "hai" (is)
        "hai": "\u0266\u025b\u02d0",
        "he": "\u0266\u025b\u02d0",
        "h": "\u0266\u025b\u02d0",
        "hain": "\u0266\u025b\u0303\u02d0",
        # "nahi" (no/not)
        "nahi": "n\u0259\u0266i\u02d0",
        "nahin": "n\u0259\u0266\u0129\u02d0",
        "nhi": "n\u0259\u0266i\u02d0",
        "ni": "n\u0259\u0266i\u02d0",
        # "kya" (what)
        "kya": "kja\u02d0",
        "kia": "kja\u02d0",
        # "yaar" (friend/dude)
        "yaar": "ja\u02d0\u027e",
        "yar": "ja\u02d0\u027e",
        "yr": "ja\u02d0\u027e",
        # "bhai" (brother)
        "bhai": "b\u02b1a\u02d0i\u02d0",
        "bhi": "b\u02b1i\u02d0",
        # "theek" (okay)
        "theek": "\u0288\u02b0i\u02d0k",
        "thik": "\u0288\u02b0i\u02d0k",
        "theik": "\u0288\u02b0i\u02d0k",
        "tik": "\u0288\u02b0i\u02d0k",
        # "dekh" (see/look)
        "dekh": "d\u032ae\u02d0k\u02b0",
        "dekho": "d\u032ae\u02d0k\u02b0o\u02d0",
        "dekhna": "d\u032ae\u02d0k\u02b0na\u02d0",
        "dekha": "d\u032ae\u02d0k\u02b0a\u02d0",
        # "kar" (do)
        "kar": "k\u0259\u027e",
        "karo": "k\u0259\u027eo\u02d0",
        "karna": "k\u0259\u027ena\u02d0",
        "kiya": "k\u026aja\u02d0",
        # "chal" (go/walk)
        "chal": "t\u0361\u0283\u0259l",
        "chalo": "t\u0361\u0283\u0259lo\u02d0",
        "chalna": "t\u0361\u0283\u0259lna\u02d0",
        # "bol" (speak)
        "bol": "bo\u02d0l",
        "bolo": "bo\u02d0lo\u02d0",
        "bolna": "bo\u02d0lna\u02d0",
        "bola": "bo\u02d0la\u02d0",
        # "aur" (and)
        "aur": "\u0254\u02d0\u027e",
        "or": "\u0254\u02d0\u027e",
        # "mein" (in/I)
        "mein": "m\u1ebd\u02d0",
        "me": "m\u1ebd\u02d0",
        "mai": "m\u025b\u0303\u02d0",
        # "toh" (then/so)
        "toh": "t\u032ao\u02d0",
        "to": "t\u032ao\u02d0",
        "tho": "t\u032ao\u02d0",
        # "lekin" (but)
        "lekin": "le\u02d0k\u026an",
        "lkn": "le\u02d0k\u026an",
        # "abhi" (now)
        "abhi": "\u0259b\u02b1i\u02d0",
        "ab": "\u0259b",
        # "ghar" (home)
        "ghar": "\u0261\u02b1\u0259\u027e",
        "ghr": "\u0261\u02b1\u0259\u027e",
        # "kaam" (work)
        "kaam": "ka\u02d0m",
        "kam": "ka\u02d0m",
        # "paisa" (money)
        "paisa": "p\u025b\u02d0sa\u02d0",
        "paise": "p\u025b\u02d0se\u02d0",
        "pesa": "p\u025b\u02d0sa\u02d0",
        # "samajh" (understand)
        "samajh": "s\u0259m\u0259d\u0361\u0292\u02b1",
        "samjh": "s\u0259m\u0259d\u0361\u0292\u02b1",
        "smjh": "s\u0259m\u0259d\u0361\u0292\u02b1",
        # "pata" (know/address)
        "pata": "p\u0259t\u032aa\u02d0",
        "pta": "p\u0259t\u032aa\u02d0",
        # "log" (people)
        "log": "lo\u02d0\u0261",
        "logo": "lo\u02d0\u0261o\u02d0",
        # "wala" (one who)
        "wala": "\u028ba\u02d0la\u02d0",
        "wali": "\u028ba\u02d0li\u02d0",
        "wale": "\u028ba\u02d0le\u02d0",
        "vala": "\u028ba\u02d0la\u02d0",
        # "khana" (food/to eat)
        "khana": "k\u02b0a\u02d0na\u02d0",
        # "pani" (water)
        "pani": "pa\u02d0ni\u02d0",
        "paani": "pa\u02d0ni\u02d0",
        # Time
        "kal": "k\u0259l",
        "aaj": "a\u02d0d\u0361\u0292",
        "aj": "a\u02d0d\u0361\u0292",
        # "zyada" (more)
        "zyada": "zja\u02d0d\u032aa\u02d0",
        "jyada": "d\u0361\u0292ja\u02d0d\u032aa\u02d0",
        # "bilkul" (absolutely)
        "bilkul": "b\u026alk\u028al",
        "bilkool": "b\u026alk\u028al",
        # "matlab" (meaning)
        "matlab": "m\u0259t\u032al\u0259b",
        "mtlb": "m\u0259t\u032al\u0259b",
        # "phir" (then/again)
        "phir": "p\u02b0\u026a\u027e",
        "fir": "p\u02b0\u026a\u027e",
        # Numbers
        "ek": "e\u02d0k",
        "do": "d\u032ao\u02d0",
        "teen": "t\u032ai\u02d0n",
        "char": "t\u0361\u0283a\u02d0\u027e",
        "panch": "pa\u02d0nt\u0361\u0283",
        # Food words
        "aloo": "aːluː", "alo": "aːluː", "aaloo": "aːluː", "alu": "aːluː",
        "matar": "məʈəɾ", "mattar": "məʈəɾ", "mutter": "məʈəɾ",
        "dal": "d̪aːl", "daal": "d̪aːl", "dhal": "d̪aːl",
        "roti": "ɾoːʈiː", "rotti": "ɾoːʈiː",
        "paneer": "pəniːɾ", "panir": "pəniːɾ", "pneer": "pəniːɾ",
        "chai": "t͡ʃaːj", "chay": "t͡ʃaːj",
        "samosa": "səmoːsaː", "samose": "səmoːseː",
        "biryani": "bɪɾjaːniː", "biriyani": "bɪɾjaːniː", "biryni": "bɪɾjaːniː",
        # Commonly wrong in auto-generation
        "bus": "bəs", "bas": "bəs",
        "mat": "mət̪", "tu": "t̪uː", "hum": "ɦəm", "tum": "t̪ʊm",
        "karra": "kəɾɾəɦaː",
    }
